# Uncomment the next line to define a global platform for your project
 platform :ios, '7.0'

target 'NHHUDExtendDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'NHHUDExtend', :path => ‘../NHHUDExtend.podspec'

  target 'NHHUDExtendDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHHUDExtendDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
